### ISSUE TITLE
No magic numbers

### ISSUE THREAD

**Issue by henrikmdev** [B-ANTONY-J/Hangman#4]
https://github.com/B-ANTONY-J/Hangman/blob/f77bd5180f80060c165f6d1660af363845af9ab9/Hangman/Program.cs#L237
https://github.com/B-ANTONY-J/Hangman/blob/f77bd5180f80060c165f6d1660af363845af9ab9/Hangman/Program.cs#L295

Make the "6" a constant so that you don't have to use the magic number "6" all the time and also so you and other people looking at your code know what "6" is referring to.

**Comment by B-ANTONY-J** [comment]
Changed Magic number of 6 to a Constant variable "EQUALS_TO_SIX".

**Comment by incredibleLeitman** [comment]
This is not a very good constant name ☝️ 
Imagine you later want to change this value to 7 then this name will confuse you so much xD

Instead you should try to name variables for what they are storing or used for: MAX_QUESSES or NUM_TRIES or something along those lines would be more appropriate

**Comment by B-ANTONY-J** [comment]
I can understand that but that's what I thought the purpose of a constant was for because it does not change values and it stays consistent through out the program along with being descriptive as to what the var does.   If I were to change this later on to a value of 7 shouldn't I just create either a NEW constant for that var of 7 or create variable specifically within that block of code that it's used in instead of altering a set constant?  I will change it but I'm just trying to make sure I have a better understanding of a Constant by your definition and how it should applied versus a variable.

**Comment by incredibleLeitman** [comment]
The idea behind having a constant value is that it basically function as a configuration value for your program: you have one single source of truth that defines the behavior of your program. Later those value will come from server responses a database or some extra configuration files, but the idea stays the same: when your program first starts it gets the values that defines the behavior and those stay consistent through the runtime of your app. And if you want to modify those values you don't have to update all places where those values are applied but only on place where it receives its value.

But don't confuse changing configuration values with updating values during runtime 👆
