### ISSUE TITLE
Correct guesses vs all guesses

### ISSUE THREAD

**Issue by henrikmdev** [B-ANTONY-J/Hangman#7]
https://github.com/B-ANTONY-J/Hangman/blob/f77bd5180f80060c165f6d1660af363845af9ab9/Hangman/Program.cs#L239

This comment says "All guesses" but it looks like you're only displaying the correct guesses. So if the user has wrong guesses, those letters won't be displayed?

**Comment by B-ANTONY-J** [comment]
All letters that are displayed here are for correct and incorrect guesses  but at the time of creation I didn't think all the way through of the naming convention of this var within the Foreach loop and the full code itself.  Let me see if I can adjust it without completely disturbing the variable and loop(s).

**Comment by B-ANTONY-J** [comment]
After reviewing my code more this comment should stay because it displays "all letters guessed" so you the user can keep track of all letters entered because the correct letters will be displayed when uncovering the letters of the word but the user will need to see "all letters" entered to avoid duplicating a guess.

**Comment by B-ANTONY-J** [comment]
After reviewing my code more this comment should stay because it displays "all letters guessed" so you the user can keep track of all letters entered because the correct letters will be displayed when uncovering the letters of the word but the user will need to see "all letters" entered to avoid duplicating a guess.

**Comment by mayisa87** [comment]
Maybe you could just rename it to "Already used letters" or "Letters used/guessed so far" or "Already guessed letterts", would be more clear for user I think. But I see, you want to print all letters the user has guessed so far.

**Comment by B-ANTONY-J** [comment]
I will change it but it doesn't really seem like it's is making the code that more efficient because it's still being defined the same way.  I will use "Letters Guessed so far"
